export const a = 'a'
export const b = 'b'
export const c = 'c'
export const d = 'd'
export const e = 'e'
export const f = 'f'
export const g = 'g'
export const h = 'h'
export const i = 'i'
export const j = 'j'
export const k = 'k'
export const l = 'l'
export default a
